export const SUCCESSFUL_AUTH = 'SUCCESSFUL_AUTH';

export const UNSUCCESSFUL_AUTH = 'UNSUCCESSFUL_AUTH';

export const CHANGE_PAGE = 'CHANGE_PAGE';

export const ADD_FEEDBACK = 'ADD_FEEDBACK';

export const SUBMISSION_SUCCESS = 'SUBMISSION_SUCCESS'

export const SUBMISSION_ERROR = 'SUBMISSION_ERROR';

export const GET_FEEDBACK = 'GET_FEEDBACK';

export const UP_VOTE = 'UP_VOTE';

export const REMOVE_VOTE = 'REMOVE_VOTE';

export const ADD_TAG_FILTER = 'ADD_TAG_FILTER';

export const REMOVE_TAG_FILTER = 'REMOVE_TAG_FILTER';

export const GET_USER = 'GET_USER';